### ISSUE TITLE
Fix nightly tests in preparation for Wagtail 2.15

### ISSUE THREAD

**Issue by zerolab** [torchbox/wagtailmedia#141]
https://github.com/torchbox/wagtailmedia/runs/3865018054?check_suite_focus=true

<details>
<summary>Test failures</summary>

```shell
............................../opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/search/backends/__init__.py:41: RemovedInWagtail216Warning: SearchBackend has been moved from wagtail.search.backends.db to wagtail.search.backends.database
  return backend_module.SearchBackend
E.EE................EE...................EEEE..EE.E.EE.E...E..........E.......E....................
======================================================================
ERROR: test_custom_ordering (tests.test_models.TestMediaQuerySet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/wagtailmedia/wagtailmedia/tests/test_models.py", line 147, in test_custom_ordering
    results = Media.objects.order_by("title").search("Test")
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/search/queryset.py", line 10, in search
    search_backend = get_search_backend(backend)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/search/backends/__init__.py", line 79, in get_search_backend
    return backend_cls(params)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/search/backends/database/__init__.py", line 9, in SearchBackend
    from .postgres.postgres import PostgresSearchBackend
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/search/backends/database/postgres/postgres.py", line 17, in <module>
    from ....models import IndexEntry
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/search/models.py", line 20, in <module>
    class Query(models.Model):
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/django/db/models/base.py", line 113, in __new__
    raise RuntimeError(
RuntimeError: Model class wagtail.search.models.Query doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

======================================================================
ERROR: test_operators (tests.test_models.TestMediaQuerySet)
----------------------------------------------------------------------
    response = get_response(request)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/admin/urls/__init__.py", line 121, in wrapper
    return view_func(request, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/admin/auth.py", line 195, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/admin/auth.py", line 61, in wrapped_view_func
    return view_func(request, *args, **kwargs)
  File "/home/runner/work/wagtailmedia/wagtailmedia/src/wagtailmedia/views/media.py", line 181, in edit
    for backend in get_search_backends():
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/search/backends/__init__.py", line 107, in <genexpr>
    return (backend for _, backend in get_search_backends_with_name(with_auto_update=with_auto_update))
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/search/backends/__init__.py", line 102, in get_search_backends_with_name
    yield backend, get_search_backend(backend)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/search/backends/__init__.py", line 79, in get_search_backend
    return backend_cls(params)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/search/backends/database/__init__.py", line 9, in SearchBackend
    from .postgres.postgres import PostgresSearchBackend
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/search/backends/database/postgres/postgres.py", line 17, in <module>
    from ....models import IndexEntry
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/search/models.py", line 20, in <module>
    class Query(models.Model):
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/django/db/models/base.py", line 113, in __new__
    raise RuntimeError(
RuntimeError: Model class wagtail.search.models.Query doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

======================================================================
ERROR: test_search (tests.test_views.TestMediaIndexView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/wagtailmedia/wagtailmedia/tests/test_views.py", line 44, in test_search
    response = self.client.get(reverse("wagtailmedia:index"), {"q": "Hello"})
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/django/test/client.py", line 742, in get
    response = super().get(path, data=data, secure=secure, **extra)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/django/test/client.py", line 396, in get
    return self.generic('GET', path, secure=secure, **{
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/admin/urls/__init__.py", line 121, in wrapper
    return view_func(request, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/admin/auth.py", line 195, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/admin/auth.py", line 61, in wrapped_view_func
    return view_func(request, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/django/views/decorators/vary.py", line 20, in inner_func
    response = func(*args, **kwargs)
  File "/home/runner/work/wagtailmedia/wagtailmedia/src/wagtailmedia/views/media.py", line 50, in index
    media = media.search(query_string)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/search/queryset.py", line 10, in search
    search_backend = get_search_backend(backend)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/search/backends/__init__.py", line 79, in get_search_backend
    return backend_cls(params)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/search/backends/database/__init__.py", line 9, in SearchBackend
    from .postgres.postgres import PostgresSearchBackend
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/search/backends/database/postgres/postgres.py", line 17, in <module>
    from ....models import IndexEntry
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/wagtail/search/models.py", line 20, in <module>
    class Query(models.Model):
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/django/db/models/base.py", line 113, in __new__
    raise RuntimeError(
RuntimeError: Model class wagtail.search.models.Query doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```
</details>

**Comment by zerolab** [comment]
fixed in #143
