### ISSUE TITLE
Missing usage_count_enabled-tag with wagtail 4.1rc1

### ISSUE THREAD

**Issue by th3hamm0r** [torchbox/wagtailmedia#180]
### Issue Summary

I've just tried wagtailmedia with the latest wagtail 4.1rc1 and I've found the following error. It seems like the tag has been removed due to the new usage reporting implementation.

```
Traceback (most recent call last):
  File "/***/lib/python3.10/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'usage_count_enabled'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/***/lib/python3.10/site-packages/asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "/***/lib/python3.10/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/***/lib/python3.10/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/***/lib/python3.10/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/***/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/***/lib/python3.10/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
...
  File "/***/lib/python3.10/site-packages/wagtail/admin/auth.py", line 62, in wrapped_view_func
    return view_func(request, *args, **kwargs)
  File "/***/lib/python3.10/site-packages/wagtailmedia/views/media.py", line 225, in edit
    return render(
  File "/***/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 95, in render
    return real_render(request, template_name, context, *args, **kwargs)
  File "/***/lib/python3.10/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/***/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/***/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/***/lib/python3.10/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/***/lib/python3.10/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/***/lib/python3.10/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/***/lib/python3.10/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/***/lib/python3.10/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/***/lib/python3.10/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/***/lib/python3.10/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/***/lib/python3.10/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/***/lib/python3.10/site-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/***/lib/python3.10/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/***/lib/python3.10/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/***/lib/python3.10/site-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/***/lib/python3.10/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/***/lib/python3.10/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/***/lib/python3.10/site-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/***/lib/python3.10/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/***/lib/python3.10/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/***/lib/python3.10/site-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/***/lib/python3.10/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/***/lib/python3.10/site-packages/django/template/base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 65: 'usage_count_enabled', expected 'endblock'. Did you forget to register or load this tag?
```

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Integrate `wagtailmedia`
3. Upload a new media and open its edit page

### Technical details

* Python version: 3.10
* Django version: 3.2
* Wagtail version: 4.1rc1
* `wagtailmedia` version: 0.11.1

**Comment by zerolab** [comment]
Thank you @th3hamm0r, I made a note about this in https://wagtailcms.slack.com/archives/C01BLUZE3C3/p1665360622686199 and is on the list of thing to fix. As always a PR supporting this would be amazing, if you have the time :D

**Comment by zerolab** [comment]
@th3hamm0r see #181

**Comment by th3hamm0r** [comment]
Thx @zerolab! 🚀 I can test it in the coming week.

**Comment by th3hamm0r** [comment]
Tested it with both 4.0 and 4.1rc1, looks good! During that, I've found some minor UI issues: #183
