### ISSUE TITLE
Revision diff comparison displays VideoBlock.render_basic error

### ISSUE THREAD

**Issue by rcoombes-gosh** [torchbox/wagtailmedia#188]
### Issue Summary

Receiving the following error when viewing a revision diff comparison that contains a video (that hasn't change between revisions)

`You need to implement VideoBlock.render_basic`

### Steps to Reproduce

1. Updated project to use wagtailmedia 0.12.0
2. View a known page comparison that contains an mp4

### Technical details

* Django Version: 3.2.16
* Python Version: 3.8.15
* Wagtail version: 3.0.3
* `wagtailmedia` version: 0.12.0
* Browser version: Chrome 106

```
Environment:

Request Method: GET
Request URL: //127.0.0.1:3000/admin/pages/507/revisions/compare/20806...20808/

Django Version: 3.2.16
Python Version: 3.8.15
Installed Applications:
['gosh.documents',
 'gosh.donations',
 'gosh.events',
 'gosh.salesforce',
 'gosh.justgiving',
 'gosh.forms',
 'gosh.forms.addressfield',
 'gosh.fundraising',
 'gosh.home',
 'gosh.images',
 'gosh.media',
 'gosh.navigation',
 'gosh.news',
 'gosh.powerofplay',
 'gosh.press',
 'gosh.search',
 'gosh.shorthand',
 'gosh.sitewide_alert',
 'gosh.standardpages',
 'gosh.taxonomy',
 'gosh.users',
 'gosh.utils',
 'gosh.archived_content',
 'gosh.data_migration',
 'wagtail.contrib.modeladmin',
 'wagtail.contrib.settings',
 'wagtail.contrib.search_promotions',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.contrib.routable_page',
 'wagtail.contrib.table_block',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.contrib.legacy.richtext',
 'wagtail',
 'el_pagination',
 'modelcluster',
 'taggit',
 'captcha',
 'wagtailcaptcha',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sitemaps',
 'pattern_library',
 'gosh.project_styleguide.apps.ProjectStyleguideConfig',
 'django_rq',
 'wagtailmenus',
 'wagtailaccessibility',
 'wagtailschemaorg',
 'wagtailquickcreate',
 'wagtail_guide',
 'wagtailmedia',
 'wagtailfontawesomesvg',
 'wagtailsharing',
 'wagtaildonate',
 'rest_framework',
 'birdbath',
 'more_itertools',
 'wagtail.contrib.styleguide',
 'django_extensions']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'gosh.donations.middleware.AttributionTrackingMiddleware',
 'gosh.utils.middleware.RequestToLowercaseMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware',
 'gosh.utils.middleware.HandleProtectionErrorMiddleware']


Template error:
In template /venv/lib/python3.8/site-packages/wagtail/admin/templates/wagtailadmin/skeleton.html, error at line 30
   You need to implement VideoBlock.render_basic
   20 :     <body id="wagtail" class="{% block bodyclass %}{% endblock %} {% if sidebar_collapsed %}sidebar-collapsed{% endif %} {% if messages %}has-messages{% endif %}">
   21 :         <div data-sprite></div>
   22 :         <script>
   23 :             function loadIconSprite() {
   24 :                 var spriteURL = '{% url "wagtailadmin_sprite" %}';
   25 :                 var revisionKey = 'wagtail:spriteRevision';
   26 :                 var dataKey = 'wagtail:spriteData';
   27 :                 var isLocalStorage = 'localStorage' in window && typeof window.localStorage !== 'undefined';
   28 : 
   29 :                 var insertIt = function (data) {
   30 :                     var spriteContainer = document.body.que rySelector('[data-s prite]');
   31 :                     spriteContainer.innerHTML = data;
   32 :                 }
   33 : 
   34 :                 var insert = function (data) {
   35 :                     if (document.body) {
   36 :                         insertIt(data)
   37 :                     } else {
   38 :                         document.addEventListener('DOMContentLoaded', insertIt.bind(null, data));
   39 :                     }
   40 :                 }


Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/venv/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.8/site-packages/pattern_library/loader_tags.py", line 38, in render
    return super().render(context)
  File "/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.8/site-packages/pattern_library/loader_tags.py", line 38, in render
    return super().render(context)
  File "/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.8/site-packages/pattern_library/loader_tags.py", line 38, in render
    return super().render(context)
  File "/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.8/site-packages/django/template/defaulttags.py", line 214, in render
    nodelist.append(node.render_annotated(context))
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.8/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/venv/lib/python3.8/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/venv/lib/python3.8/site-packages/wagtail/admin/compare.py", line 312, in htmldiff
    return StreamBlockComparison(
  File "/venv/lib/python3.8/site-packages/wagtail/admin/compare.py", line 290, in htmldiff
    block_rendered = comparison.htmlvalue(comparison.val_a)
  File "/venv/lib/python3.8/site-packages/wagtailmedia/blocks.py", line 70, in htmlvalue
    "media_item_a": self.block.render_basic(value),
  File "/venv/lib/python3.8/site-packages/wagtailmedia/blocks.py", line 57, in render_basic
    raise NotImplementedError(

Exception Type: NotImplementedError at /admin/pages/507/revisions/compare/20806...20808/
Exception Value: You need to implement VideoBlock.render_basic
```

**Comment by zerolab** [comment]
OK, had to dig deeper. The issue there is a custom `VideoBlock`

```python
class VideoBlock(AbstractMediaChooserBlock):
    @cached_property
    def field(self):
        return forms.ModelChoiceField(
            queryset=self.target_model.objects.filter(type="video"),
            widget=self.widget,
            required=self._required,
            validators=self._validators,
            help_text=self._help_text,
        )

    class Meta:
        icon = "film"
        template = "patterns/molecules/streamfield/blocks/video_block.html"

```

You will want to update that to inherit from [`wagtailmedia.blocks.VideoChooserBlock`](https://github.com/torchbox/wagtailmedia/blob/main/src/wagtailmedia/blocks.py#L111)


```python
from wagtailmedia.blocks import VideoChooserBlock


class VideoBlock(VideoChooserBlock):

    class Meta:
        icon = "film"
        template = "patterns/molecules/streamfield/blocks/video_block.html"
```

**Comment by zerolab** [comment]
Thank you for filing this @rcoombes-gosh.
Closing this based on the previous comment
