### ISSUE TITLE
Migration fails when running tests

### ISSUE THREAD

**Issue by steverowland** [torchbox/wagtailmedia#36]
The following issue appeared when running tests - the migrations is failing:

```
(envbhv2) DDE-MacBook-Pro:bhv2 dde$ python src/manage.py test project.invoices.tests --keepdb
Using existing test database for alias 'default'...
Traceback (most recent call last):
  File "src/manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/core/management/commands/test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/test/runner.py", line 601, in run_tests
    old_config = self.setup_databases()
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/test/runner.py", line 546, in setup_databases
    self.parallel, **kwargs
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/test/utils.py", line 187, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/db/backends/base/creation.py", line 69, in create_test_db
    run_syncdb=True,
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/wagtailmedia/migrations/0003_copy_media_permissions_to_collections.py", line 27, in copy_media_permissions_to_collections
    root_collection = Collection.objects.get(depth=1)
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
__fake__.DoesNotExist: Collection matching query does not exist.
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/contrib/gis/ptr.py", line 36, in __del__
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/contrib/gis/geos/libgeos.py", line 161, in __call__
  File "/Users/dde/virtualenvs/envbhv2/lib/python3.6/site-packages/django/contrib/gis/geos/libgeos.py", line 165, in get_func
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by thibaudcolas** [comment]
I would assume this is because of https://github.com/torchbox/wagtailmedia/blob/9a4112d81783cc001cb2baa19bea899222c03ed0/wagtailmedia/migrations/0003_copy_media_permissions_to_collections.py#L22-L27

…which should check whether there are collections before executing the rest of the migration?

Did you end up solving this @steverowland?

**Comment by thenewguy** [comment]
This is an old issue - closing for cleanup.  It haven't encountered it so I am thinking it has been solved or was due to some sort of local issue.  Re-open if you can provide a way to recreate the problem so it can be solved
