### ISSUE TITLE
MediaChooserPanel object has no attribute 'bind_to'

### ISSUE THREAD

**Issue by biwin** [torchbox/wagtailmedia#53]
While migrating the below model found on readme,
```
from django.db import models

from wagtail.core.models import Page
from wagtail.core.fields import RichTextField
from wagtail.admin.edit_handlers import FieldPanel

from wagtailmedia.edit_handlers import MediaChooserPanel



class BlogPageWithMedia(Page):
    author = models.CharField(max_length=255)
    media = models.ForeignKey(
        'wagtailmedia.Media',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    content_panels = Page.content_panels + [
        FieldPanel('author'),
        MediaChooserPanel('media'),
    ]
```
an exception is raised, 

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/virtualenv/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/virtualenv/lib/python3.6/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/home/virtualenv/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/virtualenv/lib/python3.6/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/virtualenv/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/virtualenv/lib/python3.6/site-packages/wagtail/admin/checks.py", line 62, in get_form_class_check
    edit_handler = cls.get_edit_handler()
  File "/home/virtualenv/lib/python3.6/site-packages/wagtail/utils/decorators.py", line 53, in __call__
    return self.value
  File "/home/virtualenv/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/virtualenv/lib/python3.6/site-packages/wagtail/utils/decorators.py", line 49, in value
    return self.fn(self.cls)
  File "/home/virtualenv/lib/python3.6/site-packages/wagtail/admin/edit_handlers.py", line 825, in get_edit_handler
    return edit_handler.bind_to(model=cls)
  File "/home/virtualenv/lib/python3.6/site-packages/wagtail/admin/edit_handlers.py", line 148, in bind_to
    new.on_model_bound()
  File "/home/virtualenv/lib/python3.6/site-packages/wagtail/admin/edit_handlers.py", line 299, in on_model_bound
    for child in self.children]
  File "/home/virtualenv/lib/python3.6/site-packages/wagtail/admin/edit_handlers.py", line 299, in <listcomp>
    for child in self.children]
  File "/home/virtualenv/lib/python3.6/site-packages/wagtail/admin/edit_handlers.py", line 148, in bind_to
    new.on_model_bound()
  File "/home/virtualenv/lib/python3.6/site-packages/wagtail/admin/edit_handlers.py", line 299, in on_model_bound
    for child in self.children]
  File "/home/virtualenv/lib/python3.6/site-packages/wagtail/admin/edit_handlers.py", line 299, in <listcomp>
    for child in self.children]
AttributeError: 'MediaChooserPanel' object has no attribute 'bind_to'


```

versions: 
```
wagtailmedia==0.3.0 (github master)
wagtail==2.5.1
Django==2.2.1
```

**Comment by thibaudcolas** [comment]
Thanks for the report @biwin. This looks like the same issue as #34 – could you try the workaround suggested there (use `BaseMediaChooserPanel` instead of `MediaChooserPanel`) and report back?

**Comment by thibaudcolas** [comment]
Closing this in favour of #34.
